(() => {
  const W=420,H=760;
  const SUPABASE_URL='https://cpifithxuojbporzhqid.supabase.co';
  const SUPABASE_KEY='sb_publishable_G_tmtpLXfntuOasLO52naA_hiYglfJK';
  const SCORE_TABLE='poop_dodge_scores';
  const CHARACTERS={
    taehoon:{name:'태훈똥',img:'https://cdn.jsdelivr.net/gh/bleejoon-creator/123@main/yanadoo-poop-dodge/v5/taehoon.webp',ability:'민첩형',desc:'드래그 추종속도 +10%',move:1.10,hitbox:1,itemPickup:1,duration:0},
    seoyoung:{name:'서영똥',img:'https://cdn.jsdelivr.net/gh/bleejoon-creator/123@main/yanadoo-poop-dodge/v5/seoyoung.webp',ability:'회피형',desc:'피격 판정 6% 감소',move:1,hitbox:.94,itemPickup:1,duration:0},
    hyunjin:{name:'현진똥',img:'https://cdn.jsdelivr.net/gh/bleejoon-creator/123@main/yanadoo-poop-dodge/v5/hyunjin.webp',ability:'아이템형',desc:'아이템 획득 범위 +14%',move:1,hitbox:1,itemPickup:1.14,duration:0},
    hyunbeom:{name:'현범똥',img:'https://cdn.jsdelivr.net/gh/bleejoon-creator/123@main/yanadoo-poop-dodge/v5/hyunbeom.webp',ability:'지속형',desc:'보호·슬로우 +0.7초',move:1,hitbox:1,itemPickup:1,duration:.7},
    wonsik:{name:'원식똥',img:'https://cdn.jsdelivr.net/gh/bleejoon-creator/123@main/yanadoo-poop-dodge/v5/wonsik.webp',ability:'예고형',desc:'빠른 똥 0.35초 사전 경고',move:1,hitbox:1,itemPickup:1,duration:0,warning:.35,new:true}
  };
  const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d'),home=document.getElementById('home'),game=document.getElementById('game'),wrap=document.getElementById('canvasWrap');
  const scoreText=document.getElementById('scoreText'),heartText=document.getElementById('heartText'),timerText=document.getElementById('timerText'),banner=document.getElementById('levelBanner'),pill=document.getElementById('statusPill'),flash=document.getElementById('flash'),hint=document.getElementById('controlsHint');
  const nicknameInput=document.getElementById('nicknameInput'),uploadScoreBtn=document.getElementById('uploadScoreBtn'),uploadStatus=document.getElementById('uploadStatus'),rankList=document.getElementById('rankList'),rankNote=document.getElementById('rankNote'),onlineRankTab=document.getElementById('onlineRankTab'),localRankTab=document.getElementById('localRankTab'),installBtn=document.getElementById('installBtn');
  const homeCharImg=document.getElementById('homeCharImg'),homeCharName=document.getElementById('homeCharName'),homeCharDesc=document.getElementById('homeCharDesc'),homeAbilityChip=document.getElementById('homeAbilityChip'),resultCharImg=document.getElementById('resultCharImg'),charGrid=document.getElementById('charGrid');
  const finalScore=document.getElementById('finalScore'),finalTime=document.getElementById('finalTime'),finalBest=document.getElementById('finalBest'),gameOverLine=document.getElementById('gameOverLine');
  const startBtn=document.getElementById('startBtn'),retryBtn=document.getElementById('retryBtn'),pauseBtn=document.getElementById('pauseBtn'),resumeBtn=document.getElementById('resumeBtn'),quitBtn=document.getElementById('quitBtn'),homeBtn=document.getElementById('homeBtn'),rankBtn=document.getElementById('rankBtn'),charBtn=document.getElementById('charBtn'),soundBtn=document.getElementById('soundBtn'),shareBtn=document.getElementById('shareBtn');
  const safeGet=k=>{try{return localStorage.getItem(k)}catch{return null}},safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch{}},clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),now=()=>performance.now()/1000;
  const fmt=t=>{const x=Math.max(0,Number(t)||0),m=Math.floor(x/60),s=Math.floor(x%60),cs=Math.floor((x*100)%100);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`};
  let selectedKey=safeGet('yanadoo-char-v5')||safeGet('yanadoo-char-v4');if(!CHARACTERS[selectedKey])selectedKey='taehoon';let selected=CHARACTERS[selectedKey];
  const playerImg=new Image();
  let soundOn=true,audioCtx=null,deferredInstallPrompt=null;
  const state={running:false,paused:false,start:0,last:0,elapsed:0,score:0,lives:1,level:1,spawnAcc:0,itemAcc:0,stormAcc:0,slowUntil:0,shieldUntil:0,objects:[],particles:[],keys:{left:false,right:false},hintTimer:0,scoreUploaded:false,dragging:false,dragStartX:0,dragStartPlayerX:0,targetX:null};
  const player={x:W/2-44,y:H-170,w:88,h:150,speed:310};
  function beep(freq=300,dur=.08,type='sine',gain=.04){if(!soundOn)return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch{}}
  function showScreen(which){home.classList.toggle('active',which==='home');game.classList.toggle('active',which==='game')}function openModal(id){document.getElementById(id).classList.add('open')}function closeModal(id){document.getElementById(id).classList.remove('open')}
  function records(){try{return JSON.parse(safeGet('yanadoo-poop-records-v5')||'[]')}catch{return []}}function saveRecord(score,time){let a=records();a.push({score:Math.floor(score),time,character:selected.name,date:new Date().toISOString()});a.sort((x,y)=>y.score-x.score||y.time-x.time);a=a.slice(0,10);safeSet('yanadoo-poop-records-v5',JSON.stringify(a));updateBest();return a[0]}function updateBest(){const b=records()[0];document.getElementById('bestHome').textContent=b?`${fmt(b.time)} · ${b.score.toLocaleString()}점`:'기록 없음'}
  function renderCharacters(){charGrid.innerHTML='';Object.entries(CHARACTERS).forEach(([key,c])=>{const b=document.createElement('button');b.className='char-card'+(key===selectedKey?' selected':'');b.innerHTML=`${key===selectedKey?'<span class="selected-mark">선택중</span>':''}${c.new?'<span class="new-mark">NEW</span>':''}<img src="${c.img}" alt="${c.name}"><b>${c.name}</b><div class="ability">${c.ability}</div><div class="detail">${c.desc}</div>`;b.onclick=()=>selectCharacter(key);charGrid.append(b)})}
  function selectCharacter(key){selectedKey=key;selected=CHARACTERS[key];safeSet('yanadoo-char-v5',key);playerImg.src=selected.img;homeCharImg.src=selected.img;resultCharImg.src=selected.img;homeCharName.textContent=selected.name;homeCharDesc.textContent=selected.desc;homeAbilityChip.textContent=`✨ ${selected.ability}`;renderCharacters();beep(620,.06,'sine',.02)}
  function getClientId(){let id=safeGet('yanadoo-poop-client-id');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`).slice(0,64);safeSet('yanadoo-poop-client-id',id)}return id}function safeNickname(){return (nicknameInput.value||'').trim().replace(/\s+/g,' ').slice(0,12)}function setUploadStatus(t,ok=false){uploadStatus.textContent=t;uploadStatus.style.color=ok?'var(--good)':'var(--muted)'}
  async function uploadOnlineScore(){if(state.scoreUploaded){setUploadStatus('이미 이번 기록은 등록했음.',true);return}const nickname=safeNickname();if(!nickname){setUploadStatus('닉네임부터 입력해줘.');nicknameInput.focus();return}safeSet('yanadoo-poop-nickname',nickname);uploadScoreBtn.disabled=true;uploadScoreBtn.textContent='등록중';setUploadStatus('온라인 랭킹에 올리는 중...');try{const res=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Prefer':'return=minimal'},body:JSON.stringify({nickname,character_name:selected.name,score:Math.floor(state.score),survival_seconds:Number(state.elapsed.toFixed(2)),client_id:getClientId()})});if(!res.ok)throw new Error(`HTTP ${res.status}`);state.scoreUploaded=true;uploadScoreBtn.textContent='등록완료';setUploadStatus('✅ 온라인 랭킹 등록 완료!',true);beep(900,.12,'sine',.035)}catch(e){uploadScoreBtn.disabled=false;uploadScoreBtn.textContent='등록';setUploadStatus('등록 실패. 인터넷 연결 확인 후 다시 눌러줘.');console.error(e)}}
  function makeRankRow(rank,name,time,score,character){const row=document.createElement('div');row.className='rank-row';const medal=document.createElement('div');medal.textContent=rank===1?'🥇':rank===2?'🥈':rank===3?'🥉':rank;const middle=document.createElement('div');middle.textContent=name;const sm=document.createElement('small');sm.textContent=`${character||'-'} · ${fmt(time)}`;middle.append(sm);const sc=document.createElement('b');sc.textContent=Number(score).toLocaleString();row.append(medal,middle,sc);return row}
  async function renderOnlineRanks(){onlineRankTab.classList.add('active');localRankTab.classList.remove('active');rankNote.textContent='온라인 기록 불러오는 중...';rankList.innerHTML='';try{const r=await fetch(`${SUPABASE_URL}/rest/v1/${SCORE_TABLE}?select=nickname,character_name,score,survival_seconds&order=score.desc,survival_seconds.desc,created_at.asc&limit=20`,{headers:{apikey:SUPABASE_KEY}});if(!r.ok)throw 0;const a=await r.json();rankNote.textContent='캐릭터 시즌 · TOP 20';if(!a.length){rankList.innerHTML='<div class="empty">아직 등록된 기록이 없음.</div>';return}a.forEach((x,i)=>rankList.append(makeRankRow(i+1,x.nickname,x.survival_seconds,x.score,x.character_name)))}catch{rankNote.textContent='온라인 랭킹을 불러오지 못했음.'}}
  function renderLocalRanks(){localRankTab.classList.add('active');onlineRankTab.classList.remove('active');const a=records();rankNote.textContent='이 기기의 새 시즌 기록';rankList.innerHTML='';if(!a.length){rankList.innerHTML='<div class="empty">아직 내 기록이 없음.</div>';return}a.forEach((x,i)=>rankList.append(makeRankRow(i+1,'내 기록',x.time,x.score,x.character)))}
  function hud(){scoreText.textContent=Math.floor(state.score).toLocaleString();heartText.textContent='❤️';timerText.textContent=fmt(state.elapsed)}function levelUp(n){state.level=n;banner.textContent=`LEVEL ${n}`;banner.classList.add('show');setTimeout(()=>banner.classList.remove('show'),1000);beep(660,.07,'square',.025)}
  function resetGame(){Object.assign(state,{running:true,paused:false,start:now(),last:now(),elapsed:0,score:0,lives:1,level:1,spawnAcc:0,itemAcc:0,stormAcc:0,slowUntil:0,shieldUntil:0,objects:[],particles:[],hintTimer:0,scoreUploaded:false,dragging:false,targetX:null});player.x=W/2-player.w/2;playerImg.src=selected.img;showScreen('game');closeModal('gameOverModal');closeModal('pauseModal');hint.classList.remove('hide');uploadScoreBtn.disabled=false;uploadScoreBtn.textContent='등록';setUploadStatus('');hud();beep(520,.09,'square',.025);requestAnimationFrame(loop)}
  function spawnPoop(kind){let s=rnd(29,47),v=rnd(135,185)+state.level*12+Math.min(58,state.elapsed*.7);if(kind==='fast')v*=1.25;const delay=(kind==='fast'&&selected.warning)?selected.warning:0;state.objects.push({type:'poop',kind:kind||'normal',x:rnd(6,W-s-6),y:-s-8,w:s,h:s,vy:v,rot:rnd(0,6),spin:rnd(-2.2,2.2),delay})}function spawnItem(){const types=['tissue','shield','slow'],kind=types[Math.floor(Math.random()*types.length)];state.objects.push({type:'item',kind,x:rnd(20,W-55),y:-55,w:44,h:44,vy:rnd(115,145),bob:rnd(0,6.2)})}
  function playerHitbox(){const shrink=.62*selected.hitbox,w=player.w*shrink,h=player.h*.68*selected.hitbox;return{x:player.x+(player.w-w)/2,y:player.y+player.h-h-5,w,h}}function rectHit(a,b,pad=0){return a.x<b.x+b.w-pad&&a.x+a.w>b.x+pad&&a.y<b.y+b.h-pad&&a.y+a.h>b.y+pad}function itemBox(){const factor=selected.itemPickup,w=player.w*.78*factor,h=player.h*.82*factor;return{x:player.x+(player.w-w)/2,y:player.y+player.h-h,w,h}}
  function burst(x,y,emoji,n=6){for(let i=0;i<n;i++)state.particles.push({x,y,emoji,size:rnd(13,23),vx:rnd(-110,110),vy:rnd(-170,-55),age:0,life:rnd(.35,.75)})}let pillTimer;function showPill(text,ms){pill.textContent=text;pill.classList.add('on');clearTimeout(pillTimer);pillTimer=setTimeout(()=>pill.classList.remove('on'),ms)}
  function itemPickup(o,t){if(o.kind==='tissue'){state.objects=state.objects.filter(x=>x.type!=='poop');showPill('🧻 화면 정리!',1300);burst(o.x,o.y,'🧻',8);beep(760,.1,'square',.035)}else if(o.kind==='shield'){const d=5+selected.duration;state.shieldUntil=t+d;showPill(`🛡️ ${d.toFixed(1)}초 무적!`,Math.round(d*1000)+100);burst(o.x,o.y,'🛡️',7);beep(880,.12,'sine',.04)}else if(o.kind==='slow'){const d=5+selected.duration;state.slowUntil=t+d;showPill(`🐌 ${d.toFixed(1)}초 슬로우!`,Math.round(d*1000)+100);burst(o.x,o.y,'❄️',7);beep(620,.15,'sine',.035)}}
  function endGame(){if(!state.running)return;state.running=false;const best=saveRecord(state.score,state.elapsed);finalScore.textContent=Math.floor(state.score).toLocaleString();finalTime.textContent=fmt(state.elapsed);finalBest.textContent=best.score.toLocaleString();gameOverLine.textContent=`${selected.name} · ${state.elapsed>=60?'1분 넘겼다. 꽤 잘 버텼음.':state.elapsed>=30?'오 생각보다 오래 버텼네.':'한 판 더 하면 기록 깰 듯.'}`;nicknameInput.value=safeGet('yanadoo-poop-nickname')||'';resultCharImg.src=selected.img;beep(120,.35,'sawtooth',.05);setTimeout(()=>openModal('gameOverModal'),220)}
  function update(dt,t){state.elapsed=t-state.start;state.score+=dt*(100+state.level*9);const nextLevel=Math.min(6,1+Math.floor(state.elapsed/18));if(nextLevel!==state.level)levelUp(nextLevel);state.hintTimer+=dt;if(state.hintTimer>3.2)hint.classList.add('hide');let desired=null;if(state.targetX!=null)desired=state.targetX;const dir=(state.keys.left?-1:0)+(state.keys.right?1:0);if(dir)desired=player.x+dir*player.speed*selected.move*dt*1.25;if(desired!=null){const maxStep=player.speed*selected.move*dt,delta=clamp(desired-player.x,-maxStep,maxStep);player.x+=delta}player.x=clamp(player.x,5,W-player.w-5);let spawnInterval;if(state.elapsed<15)spawnInterval=1.05;else if(state.elapsed<30)spawnInterval=.82;else if(state.elapsed<45)spawnInterval=.66;else spawnInterval=Math.max(.32,.62-(state.elapsed-45)*.0035);state.spawnAcc+=dt;if(state.spawnAcc>=spawnInterval){state.spawnAcc=0;spawnPoop()}state.itemAcc+=dt;if(state.itemAcc>=rnd(8.5,12.5)){state.itemAcc=0;spawnItem()}state.stormAcc+=dt;if(state.level>=4&&state.stormAcc>20){state.stormAcc=0;showPill('⚠️ 똥폭풍!',1800);for(let i=0;i<5+state.level;i++)setTimeout(()=>state.running&&spawnPoop(i%3===0?'fast':null),i*170)}const slow=t<state.slowUntil?.58:1,pbox=playerHitbox(),ibox=itemBox();for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i];if(o.type==='poop'&&o.delay>0){o.delay=Math.max(0,o.delay-dt)}else{o.y+=o.vy*slow*dt}if(o.type==='poop'){o.rot+=o.spin*dt;if(t>=state.shieldUntil&&rectHit(pbox,o,5)){flash.classList.remove('hit');void flash.offsetWidth;flash.classList.add('hit');burst(o.x+o.w/2,o.y+o.h/2,'💩',6);state.objects.splice(i,1);endGame();return}}else if(rectHit(ibox,o,1)){itemPickup(o,t);state.objects.splice(i,1);continue}if(o.y>H+70)state.objects.splice(i,1)}for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.age+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;if(p.age>=p.life)state.particles.splice(i,1)}hud()}
  function drawBackground(t){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#bfe7ff');g.addColorStop(.5,'#eaf8ff');g.addColorStop(.72,'#f8e9c8');g.addColorStop(1,'#a9cf79');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='rgba(255,255,255,.45)';for(let i=0;i<5;i++){const x=(i*103+(t*7)%530)-70,y=95+(i%2)*74;ctx.beginPath();ctx.arc(x,y,22,0,Math.PI*2);ctx.arc(x+24,y-9,27,0,Math.PI*2);ctx.arc(x+50,y,19,0,Math.PI*2);ctx.fill()}ctx.fillStyle='#8dbb62';ctx.fillRect(0,H-90,W,90)}function drawPoop(size){const k=size/46;ctx.scale(k,k);ctx.lineJoin='round';ctx.strokeStyle='#5b2c0d';ctx.lineWidth=1.8;ctx.fillStyle='#9a4d16';const blob=(x,y,rx,ry)=>{ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();ctx.stroke()};blob(0,10,18,9);blob(0,2,14.5,8.5);blob(0,-5,10.5,7);ctx.beginPath();ctx.moveTo(-4,-9);ctx.quadraticCurveTo(3,-18,5,-8);ctx.quadraticCurveTo(8,-5,3,-3);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(-4,-3,3.2,3.8,0,0,Math.PI*2);ctx.ellipse(4,-3,3.2,3.8,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#24150d';ctx.beginPath();ctx.arc(-3.4,-2.4,1.25,0,Math.PI*2);ctx.arc(3.4,-2.4,1.25,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#24150d';ctx.lineWidth=1.6;ctx.beginPath();ctx.arc(0,5,5,0.12*Math.PI,.88*Math.PI);ctx.stroke()}
  function drawObject(o,t){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);if(o.type==='poop'){if(o.delay>0){ctx.globalAlpha=.82;ctx.fillStyle='#ff4d4f';ctx.beginPath();ctx.arc(0,0,Math.max(10,o.w*.28),0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(13,Math.floor(o.w*.42))}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('!',0,1)}else{ctx.rotate(o.rot);drawPoop(o.w)}}else{const e={tissue:'🧻',shield:'🛡️',slow:'🐌'}[o.kind];ctx.translate(0,Math.sin(t*5+o.bob)*3);ctx.font='35px Apple Color Emoji,Segoe UI Emoji,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(e,0,0)}ctx.restore()}
  function drawPlayer(t){ctx.save();ctx.shadowColor='rgba(0,0,0,.25)';ctx.shadowBlur=9;ctx.shadowOffsetY=6;if(playerImg.complete&&playerImg.naturalWidth){const ar=playerImg.naturalWidth/playerImg.naturalHeight,maxW=88,maxH=150;let dw=maxW,dh=dw/ar;if(dh>maxH){dh=maxH;dw=dh*ar}const dx=player.x+(player.w-dw)/2,dy=player.y+player.h-dh;ctx.drawImage(playerImg,dx,dy,dw,dh)}if(t<state.shieldUntil){ctx.shadowColor='transparent';ctx.strokeStyle='rgba(78,179,255,.9)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(player.x+player.w/2,player.y+player.h/2,52,0,Math.PI*2);ctx.stroke()}ctx.restore()}function draw(t){drawBackground(t);state.objects.forEach(o=>drawObject(o,t));drawPlayer(t);for(const p of state.particles){ctx.globalAlpha=1-p.age/p.life;ctx.font=`${p.size}px Apple Color Emoji,Segoe UI Emoji,sans-serif`;ctx.fillText(p.emoji,p.x,p.y);ctx.globalAlpha=1}if(t<state.slowUntil){ctx.fillStyle='rgba(100,190,255,.055)';ctx.fillRect(0,0,W,H)}}function loop(ms){if(!state.running||state.paused)return;const t=ms/1000,dt=Math.min(.032,t-state.last);state.last=t;update(dt,t);draw(t);if(state.running)requestAnimationFrame(loop)}
  function pause(){if(!state.running||state.paused)return;state.paused=true;openModal('pauseModal')}function resume(){if(!state.running)return;closeModal('pauseModal');state.paused=false;state.last=now();requestAnimationFrame(loop)}
  function showInstallGuide(){const steps=document.getElementById('installSteps'),text=document.getElementById('installGuideText');steps.innerHTML='';const ios=/iPad|iPhone|iPod/.test(navigator.userAgent),items=ios?['Safari에서 아래 공유 버튼 누르기','메뉴에서 “홈 화면에 추가” 선택','오른쪽 위 “추가” 누르면 완료']:['Chrome 메뉴(⋮) 열기','“앱 설치” 또는 “홈 화면에 추가” 선택','설치 누르면 일반 앱처럼 실행 가능'];text.textContent=ios?'아이폰은 Safari에서 홈 화면에 추가하면 됨.':'브라우저 설치창이 안 뜨면 아래 순서대로 하면 됨.';items.forEach((s,i)=>{const d=document.createElement('div');d.className='install-step';d.textContent=`${i+1}. ${s}`;steps.append(d)});openModal('installModal')}async function installApp(){if(window.matchMedia('(display-mode: standalone)').matches||navigator.standalone){showPill('✅ 이미 앱으로 실행 중',1500);return}if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;return}showInstallGuide()}
  wrap.addEventListener('pointerdown',e=>{if(!state.running||state.paused)return;wrap.setPointerCapture?.(e.pointerId);const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width;state.dragging=true;state.dragStartX=x;state.dragStartPlayerX=player.x;state.targetX=player.x;hint.classList.add('hide')});wrap.addEventListener('pointermove',e=>{if(!state.dragging)return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width;state.targetX=clamp(state.dragStartPlayerX+(x-state.dragStartX),5,W-player.w-5)});const endDrag=()=>{state.dragging=false;state.targetX=null};wrap.addEventListener('pointerup',endDrag);wrap.addEventListener('pointercancel',endDrag);
  addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key)){state.keys.left=true;e.preventDefault()}if(['ArrowRight','d','D'].includes(e.key)){state.keys.right=true;e.preventDefault()}if(e.key==='Escape'&&state.running){state.paused?resume():pause()}});addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))state.keys.left=false;if(['ArrowRight','d','D'].includes(e.key))state.keys.right=false});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused)pause()});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(console.error));
  startBtn.onclick=resetGame;retryBtn.onclick=resetGame;pauseBtn.onclick=pause;resumeBtn.onclick=resume;quitBtn.onclick=()=>{state.running=false;closeModal('pauseModal');showScreen('home');updateBest()};homeBtn.onclick=()=>{closeModal('gameOverModal');showScreen('home');updateBest()};rankBtn.onclick=()=>{openModal('rankModal');renderOnlineRanks()};charBtn.onclick=()=>{renderCharacters();openModal('charModal')};installBtn.onclick=installApp;uploadScoreBtn.onclick=uploadOnlineScore;onlineRankTab.onclick=renderOnlineRanks;localRankTab.onclick=renderLocalRanks;nicknameInput.addEventListener('keydown',e=>{if(e.key==='Enter')uploadOnlineScore()});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));soundBtn.onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'🔊':'🔇'};shareBtn.onclick=async()=>{const txt=`💩 야나두 똥피하기\n${selected.name}으로 ${fmt(state.elapsed)} 생존 · ${Math.floor(state.score).toLocaleString()}점\n이 기록 넘을 수 있냐?`;try{if(navigator.share)await navigator.share({title:'야나두 똥피하기',text:txt,url:location.href});else{await navigator.clipboard.writeText(txt+'\n'+location.href);showPill('📋 결과 복사 완료!',1500)}}catch{}};
  selectCharacter(selectedKey);nicknameInput.value=safeGet('yanadoo-poop-nickname')||'';updateBest();drawBackground(0);playerImg.onload=()=>drawPlayer(0);
})();